name: 'Terraform Cleanup'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to cleanup (dev/staging/prod)'
        required: true
        type: choice
        options:
        - dev
        - staging
        - prod

permissions:
  contents: read

env:
  TF_LOG: INFO
  AWS_REGION: 'us-east-1'
  TF_WORKING_DIR: 'src'

jobs:
  terraform-cleanup:
    name: 'Terraform Cleanup'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.8.2'

    - name: Terraform Init
      run: terraform init -input=false -backend-config="../environments/${{ github.event.inputs.environment }}/backend.tfvars"
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Select workspace
      run: terraform workspace select "${{ github.event.inputs.environment }}"
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Destroy
      run: terraform destroy -input=false -var-file="../environments/${{ github.event.inputs.environment }}/terraform.tfvars" -auto-approve
      working-directory: ${{ env.TF_WORKING_DIR }}

